/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sallu' at '20/2/16 4:10 PM' with Gradle 2.11
 *
 * @author sallu, @date 20/2/16 4:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
